<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Chiaroscuro-$(RuntimeIdentifier)</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Standalone)' == 'true'">
    <AssemblyName>Chiaroscuro-$(RuntimeIdentifier)-standalone</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chiaroscuro.UI\Chiaroscuro.UI.csproj" />
  </ItemGroup>
</Project>
