<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmMainJSPath>wwwroot/main.js</WasmMainJSPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" Version="12.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chiaroscuro.UI\Chiaroscuro.UI.csproj" />
  </ItemGroup>

</Project>
